### ISSUE TITLE
All builds are pending. 

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#1]
I've got 2 weeks of builds on awesome code that all say "pending".
https://awesomecode.io/projects/94

**Comment by flyerhzm** [comment]
@Br3nda thanks for reporting, our job queue was stuck, it's fixed now.

**Comment by Br3nda** [comment]
It did one run -- is it stuck again?

**Comment by flyerhzm** [comment]
The Open Source Plan only allows 100 builds per month and you have already reached, your builds will run next month or you can upgrade your account.

<img width="269" alt="screen shot 2018-05-25 at 9 18 06 am" src="https://user-images.githubusercontent.com/66836/40521146-9bf9eb4c-5ffc-11e8-915f-ace21857c53e.png">

That reminds us to make a better UI and send an email notification, thanks.

**Comment by Br3nda** [comment]
oh cool. -- i have lots of questions. is it $10/month and then *all* my organisations get unlimited builds?

**Comment by flyerhzm** [comment]
@Br3nda if the repos are created by you on awesomecode.io, yes, you get all unlimited builds for them.

We are trying to change it to "if you are the owner of the repos, then you get all unlimited builds for them".
