### ISSUE TITLE
links to configure broken on github pull requests.

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#10]
following a "click here to configure" link from https://github.com/Growstuff/growstuff/pull/2508

it leads to https://awesomecode.io//repos/Growstuff/growstuff/lint_configs/ruby/20531

that page is a mostly blank page (there's a menu, and footer, but no other content, no console errors)
if i edit the two slashes `//` in the url to `/`, then the app works as expected

**Comment by flyerhzm** [comment]
@Br3nda thanks for reporting, we have fixed it, the link is working for new PRs now.
