### ISSUE TITLE
how to delete a project?

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#2]
i renamed a github repo -- and had to set it up again on awesomecode
Now i have the project there twice.
The old name
https://awesomecode.io/projects/81

the new name
https://awesomecode.io/projects/93

How do i delete a repo from awesomecode?

**Comment by flyerhzm** [comment]
@Br3nda there's no way to delete a repo yet, but it will a new feature to add, and we may add "rename a repo" feature.

**Comment by flyerhzm** [comment]
@Br3nda We have added "delete a repository" feature, please go to the bottom of page https://awesomecode.io/projects/81/edit, then you'll see the delete button.
