### ISSUE TITLE
Can awesomecode.io run on other branches? 

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#5]
The settings hint that it can run on branches that are not the default on github for that repo. But I can't work out how.

The pushes to other branches appear as "ignored".
https://awesomecode.io/projects/57/builds/23399

**Comment by Br3nda** [comment]
Worked it out, it's part of the professional prescription. That info is a little bit hidden.

**Comment by flyerhzm** [comment]
@Br3nda we'll make it clear.
