### ISSUE TITLE
css linting checks not running

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#6]
I've added a very messy css file to git master - but awesomecode.io has found no issues with it.
The file is here:
https://github.com/WhareHauora/wharehauora-server/blob/master/app/assets/stylesheets/style.css

and the awesomecode.io project is here
https://awesomecode.io/projects/57

No css issues have ever been found in the project.
I have enabled all configs for css.

**Comment by flyerhzm** [comment]
@Br3nda just let you know it's already on my plate, I'll do it first after my vacation.

**Comment by flyerhzm** [comment]
@Br3nda it should be fixed, please try run the build again

**Comment by Br3nda** [comment]
Fixed
