### ISSUE TITLE
infinite redirects on login = can't log in new sessions

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#7]
Signing in new sessions, i get infinite redirects. I've retried in an incognito window too.

![image](https://user-images.githubusercontent.com/12266/46634943-2b3e0400-cbaf-11e8-931c-4a72e9af8059.png)

**Comment by flyerhzm** [comment]
@Br3nda I can't reproduce this issue, could you clear browser cookie and cache then try login again?

**Comment by Br3nda** [comment]
Tried that. I was incognito window too, so there shouldn't be any cookies.
