### ISSUE TITLE
Badge links = 404

### ISSUE THREAD

**Issue by Br3nda** [xinminlabs/awesomecode-issues#8]
I copied the markdown from awesomecode.io into a project readme.
The link on the badge is https://awesomecode.io/projects/111

However this is a 404 page.

**Comment by flyerhzm** [comment]
@Br3nda sorry, I should have sent an email that we have changed project url, will do after my vacation.

For project 111, the new markdown url is here https://awesomecode.io/repos/ServiceInnovationLab/Piccolo/notifications

**Comment by Br3nda** [comment]
Thanks - i worked out the URL -- but your settings -> notifications -> badges section still gives the old URLs

**Comment by flyerhzm** [comment]
@Br3nda I checked the badges section, the markdown url is `[![AwesomeCode Status for ServiceInnovationLab/Piccolo](https://awesomecode.io/projects/431b2572-acad-4e10-9cbd-2db7cf14276c/status)](https://awesomecode.io/repos/ServiceInnovationLab/Piccolo)`, which is correct.

**Comment by Br3nda** [comment]
There's more 404s. On PRs created by awesomecode.io, there's a description with a link to configure it. Those lead to a 404.

For example
https://github.com/ServiceInnovationLab/Piccolo/pull/64

**Comment by Br3nda** [comment]
The link is the pr it's to `https://awesomecode.io/repos/ServiceInnovationLab/Piccolo/javascript_configs/15085` which is a default rails 404 page

**Comment by flyerhzm** [comment]
@Br3nda it's also fixed.

**Comment by flyerhzm** [comment]
@Br3nda it is expected to render 404 if you are not authenticated, we'll change 404 page to make more sense
